//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_CLIENTES
    {
        public int DATOS_CLIENTE_ID { get; set; }
        public int CLIENTE_RUT { get; set; }
        public string DATOS_CLIENTE_CELULAR { get; set; }
        public string DATOS_CLIENTE_FONO { get; set; }
        public string DATOS_CLIENTE_EMAIL { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
