//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCIONES()
        {
            this.UBICACIONES = new HashSet<UBICACIONES>();
        }
    
        public int DIRECCION_ID { get; set; }
        public int COMUNA_ID { get; set; }
        public string DIRECCION_DES { get; set; }
        public Nullable<double> DIRECCION_LATITUD { get; set; }
        public Nullable<double> DIRECCION_LONGITUD { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual COMUNAS COMUNAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UBICACIONES> UBICACIONES { get; set; }
    }
}
