//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTOS()
        {
            this.DETALLES_EVENTOS = new HashSet<DETALLES_EVENTOS>();
            this.RUTAS = new HashSet<RUTAS>();
        }
    
        public int EVENTO_ID { get; set; }
        public int TIPO_EVENTO_ID { get; set; }
        public int CLIENTE_RUT { get; set; }
        public int MAQUINA_ID { get; set; }
        public Nullable<int> ESTADO_ID { get; set; }
        public System.DateTime EVENTO_FECHA_HORA { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_EVENTOS> DETALLES_EVENTOS { get; set; }
        public virtual ESTADOS_EVENTOS ESTADOS_EVENTOS { get; set; }
        public virtual MAQUINAS MAQUINAS { get; set; }
        public virtual TIPOS_EVENTOS TIPOS_EVENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUTAS> RUTAS { get; set; }
    }
}
