//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_USUARIOS
    {
        public int ID { get; set; }
        public int TIPO_USUARIO_ID { get; set; }
        public int USUARIO_RUT { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual TIPOS_USUARIOS TIPOS_USUARIOS { get; set; }
    }
}
