//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_HORARIOS_UBICACION
    {
        public int ID { get; set; }
        public int ID_HORARIO { get; set; }
        public int UBICACION_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual HORARIOS_UBICACIONES HORARIOS_UBICACIONES { get; set; }
        public virtual UBICACIONES UBICACIONES { get; set; }
    }
}
