//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIOS_UBICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HORARIOS_UBICACIONES()
        {
            this.HISTORIAL_HORARIOS_UBICACION = new HashSet<HISTORIAL_HORARIOS_UBICACION>();
        }
    
        public int ID_HORARIO { get; set; }
        public Nullable<System.TimeSpan> HORA_APERTURA { get; set; }
        public Nullable<System.TimeSpan> HORA_CIERRE { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_HORARIOS_UBICACION> HISTORIAL_HORARIOS_UBICACION { get; set; }
    }
}
