//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAQUINAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAQUINAS()
        {
            this.EQUIPOS_INSTALADOS = new HashSet<EQUIPOS_INSTALADOS>();
            this.EVENTOS = new HashSet<EVENTOS>();
        }
    
        public int MAQUINA_ID { get; set; }
        public string MAQUINA_SERIE { get; set; }
        public int MODELO_ID { get; set; }
        public Nullable<int> MARCA_ID { get; set; }
        public System.DateTime MAQUINA_FEC_FABRI { get; set; }
        public Nullable<bool> MAQUINA_ENUSO { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS_INSTALADOS> EQUIPOS_INSTALADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTOS> EVENTOS { get; set; }
        public virtual MODELOS MODELOS { get; set; }
        public virtual MARCAS MARCAS { get; set; }
    }
}
