//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UBICACIONES()
        {
            this.CONTACTOS = new HashSet<CONTACTOS>();
            this.EQUIPOS_INSTALADOS = new HashSet<EQUIPOS_INSTALADOS>();
            this.HISTORIAL_HORARIOS_UBICACION = new HashSet<HISTORIAL_HORARIOS_UBICACION>();
        }
    
        public int UBICACION_ID { get; set; }
        public int DIRECCION_ID { get; set; }
        public string UBICACION_DESCRIPCION { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTOS> CONTACTOS { get; set; }
        public virtual DIRECCIONES DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPOS_INSTALADOS> EQUIPOS_INSTALADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_HORARIOS_UBICACION> HISTORIAL_HORARIOS_UBICACION { get; set; }
    }
}
