//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_rest_sgmw
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.HISTORIAL_USUARIOS = new HashSet<HISTORIAL_USUARIOS>();
            this.RUTAS = new HashSet<RUTAS>();
        }
    
        public int USUARIO_RUT { get; set; }
        public string USUARIO_DV { get; set; }
        public string USUARIO_USERNAME { get; set; }
        public string USUARIO_PASSWORD { get; set; }
        public string USUARIO_NOMBRE { get; set; }
        public string USUARIO_PATERNO { get; set; }
        public string USUARIO_MATERNO { get; set; }
        public System.DateTime USUARIO_NACIMIENTO { get; set; }
        public int USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_USUARIOS> HISTORIAL_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUTAS> RUTAS { get; set; }
    }
}
